config/routes.rb
Rails.application.routes.draw do

root "restaurants#show"
resources :restaurants

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  def self.search(search)
    where(city: search)
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

def create

end

def new

end


def index
  @restaurants = Restaurant.all
  if params[:search]
    @restaurants = Restaurant.search(params[:search].titlecase).order("name DESC")
    else
    @restaurants = Restaurant.all.order("name DESC")

  end
end


def show
# @restaurants = Restaurant.all

end

def update
end

def destroy
end








end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Happyhour</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    





  </body>
</html>

app/views/restaurants/index.html.erb
<h1>HAPPY RESTAURANTS</h1>
<div class = "restaurants">

<% @restaurants.each do |res| %>
  <li><p> <%= link_to res.name, "http://#{res.website}", :target => "_blank" %> </p> </li>
  <p> Address:<%= res.address %> </p> <br>
  <p> Phone Number:<%= res.telephone %> </p> <br>
  <p> Days of the week:<%= res.day_of_week%> </p>


<% end %>

 <% if @restaurants.blank? %>
   <h4>There are no restaurants in  <%= params[:search] %>.</h4>

<img src="https://media.giphy.com/media/l8XYZYdlOHSrS/giphy.gif" alt="I Love Lucy" style="width:500px;height:500px;">
 <% end %>



</div>

app/views/restaurants/show.html.erb
<h1>HAPPY HOUR</h1>



<%= form_tag(restaurants_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Restaurants by City" %>
<%= submit_tag "Search", :name => nil %>

<% end %>



<div class="buttons">